# Generated by Django 2.0.7 on 2018-08-01 21:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloadDate', models.DateTimeField(auto_now_add=True)),
                ('num_records', models.IntegerField(default=0)),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('groupToken', models.CharField(max_length=100)),
                ('recycle', models.BooleanField(default=True)),
                ('unique_id', models.BooleanField(default=True)),
                ('groupSessions', models.TextField(default='')),
                ('numTokens', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)])),
                ('totalTokens', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)])),
                ('user', models.CharField(max_length=100)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionToken', models.CharField(max_length=100)),
                ('eventType', models.CharField(max_length=100)),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
                ('dataLog', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionToken', models.CharField(max_length=100)),
                ('hit_count', models.IntegerField(default=0)),
                ('locked', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('securityLog', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionToken', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('configFile', models.TextField()),
                ('lastStarted', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.CharField(max_length=100)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exp.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('appletName', models.CharField(max_length=100)),
                ('consentJSON', models.TextField()),
                ('participants', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='sessionKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.Session'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exp.Study'),
        ),
        migrations.AddField(
            model_name='download',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exp.Experiment'),
        ),
    ]
