# Generated by Django 2.0.7 on 2018-08-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0002_download_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='downloadSince',
            field=models.CharField(default='All', max_length=100),
            preserve_default=False,
        ),
    ]
