# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 15:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0013_auto_20160222_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokengeneration',
            name='mturk_amount',
        ),
        migrations.RemoveField(
            model_name='tokengeneration',
            name='mturk_description',
        ),
        migrations.RemoveField(
            model_name='tokengeneration',
            name='mturk_frame_size',
        ),
        migrations.RemoveField(
            model_name='tokengeneration',
            name='mturk_title',
        ),
        migrations.AddField(
            model_name='tokengeneration',
            name='totalTokens',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tokengeneration',
            name='numTokens',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)]),
        ),
    ]
