# Generated by Django 2.0.7 on 2018-08-01 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('upload_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('upload_user', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('file', models.FileField(upload_to='')),
                ('contents', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZipUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.FileField(upload_to='zip_tmp/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('upload_user', models.CharField(max_length=100)),
                ('exp_restrict', models.BooleanField(default=False)),
                ('exp_name', models.CharField(blank=True, max_length=100)),
                ('exp_recycle', models.BooleanField(default=True)),
                ('exp_unique_id', models.BooleanField(default=True)),
                ('image_dir', models.CharField(blank=True, max_length=100)),
                ('image_dir_choice', models.CharField(blank=True, max_length=100)),
                ('exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exp.Experiment')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exp.Study')),
            ],
        ),
    ]
