# Generated by Django 2.0.7 on 2018-08-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filer',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
