# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('upload_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expName', models.CharField(max_length=100)),
                ('repetitions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ZipUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.FileField(upload_to=b'zip_tmp/')),
                ('group', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('upload_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='uploadevent',
            name='sourceFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filer.ZipUpload'),
        ),
    ]
