# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0016_session_laststarted'),
        ('filer', '0002_auto_20160710_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipupload',
            old_name='group',
            new_name='exp_name',
        ),
        migrations.AddField(
            model_name='zipupload',
            name='exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exp.Experiment'),
        ),
        migrations.AddField(
            model_name='zipupload',
            name='exp_recycle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zipupload',
            name='exp_unique_id',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zipupload',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exp.Study'),
        ),
    ]
