# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0004_zipupload_exp_restrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipupload',
            name='exp_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
