# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0005_auto_20160717_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipupload',
            name='image_dir',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zipupload',
            name='image_dir_choice',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
