# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-24 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160722_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadevent',
            name='sourceFile',
        ),
        migrations.AlterField(
            model_name='zipupload',
            name='image_dir',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zipupload',
            name='image_dir_choice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='UploadEvent',
        ),
    ]
