"""
Django settings for internet_exp project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# SECURITY WARNING: don't run with debug turned on in production!
#  PRODUCTION true for online deployment, set False for local development server testing
DEBUG = True
PRODUCTION = False

if PRODUCTION:
    from .local_settings import *
else:
    # low security values for local development
    SECRET_KEY = 'databasesecretkeygoeshere'
    ALLOWED_HOSTS = ['127.0.0.1']


# Application definition
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'exp',
    'filer',
)

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]

ROOT_URLCONF = 'empirical.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'empirical.wsgi.application'


# Database, RDS/MySql for online deployment, local sqlite for development
if PRODUCTION:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'empirical',
            'HOST': 'empirical-db.cluster-ctdatekjj4bm.us-west-2.rds.amazonaws.com',
            'USER': 'dbadmin',
            'PASSWORD': SECRET_KEY,
            # PORT 3306, myseql-5-6
        }
    }
    CSRF_COOKIE_DOMAIN='.reberlab.org'
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGIN_URL='/accounts/login/'
#LOGIN_REDIRECT_URL = '/home/'

VERSION="Empirical 0.41 April 2019"

if PRODUCTION:
    STATIC_ROOT = os.path.join(BASE_DIR,'static')
else:
    STATICFILES_DIRS = (
        os.path.join(BASE_DIR,"static"),
    )

STATIC_URL = '/static/'
MEDIA_URL = '/images/'
MEDIA_ROOT = os.path.join(BASE_DIR,'images/')
ZIP_TMP = 'zip_tmp/'

# The filer index view will automatically clean up ZIP_TMP deleting older files
# this is the maximum number to be kept on disk
ZIP_RETAIN = 20

# Security values
SECURITY_UPLOAD_MIN_TIME = 2.0
MAX_SECURITY_COUNT = 5
